Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    TemplateConfigs:
      - Name: 单机版
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - cn-hongkong
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: docker compose deploy
    Image: 'resources/icons/service_logo.png'